version: "3.6"

services:
  postgres:
    build: "./postgres"
    restart: "always"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "54321"
  book:
    build: "."
    command: "Phonebook"
    depends_on:
      - "postgres"
    ports:
      - "8080"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      HTTP_PROXY: ""
